apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  replicas: 3
  selector:
    matchLabels:
      run: inventory
  template:
    metadata:
      labels:
        run: inventory
    spec:
      containers:
        - name: inventory
          image: ghcr.io/wooseokchoi-kurly/kurly-inventory:releases-v.0.0.1
          ports:
            - containerPort: 8080
