#h2 console
spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  #  h2 db
  datasource:
    url: jdbc:h2:mem:inventoryDB
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show_sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false